# codecov.yml
# Validate with:
#   curl -X POST --data-binary @codecov.yml https://codecov.io/validate

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "30...80"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - composables/
      - stores/
      - components/
      - pages/
    carryforward: true
