version: '3.7'

services:
  app:
    build: .
    image: awesome-nexa
    container_name: awesome-nexa
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - CMC_API_KEY=${CMC_API_KEY} # change this to match your system's ENV
  couchdb:
      image: couchdb
      restart: always
      ports:
        - '127.0.0.1:5984:5984'
      environment:
        - COUCHDB_USER=${COUCHDB_USER}
        - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      volumes:
          - ./data:/opt/couchdb/data
